/**
 * Created by gcharles on 3/23/16.
 */
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
//
function euler002() {
   let even = x => x % 2 == 0;

   // Fibonacci generator
   function* fibonacci() {
      let a = 1;
      let b = 2;

      while (true) {
         let result = a;
         a = b;
         b = a + result;

         yield result;
      }
   }

   let fib = fibonacci();
   let sum = 0;

   for (let val = fib.next().value; val <= 4000000; val = fib.next().value) {
      if (even(val)) {
         sum += val;
      }
   }

   return sum;
}
